<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ad59343a-0dd5-44ca-91ec-389a00d188e2</groupId>
    <artifactId>emp-onboarding-system-api</artifactId>
    <version>1.0.0</version>
    <packaging>mule-application</packaging>

    <name>emp-onboarding-system-api</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <app.runtime>4.9.0</app.runtime>
        <mule.maven.plugin.version>4.3.0</mule.maven.plugin.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.2.0</version>
            </plugin>

            <plugin>
                <groupId>org.mule.tools.maven</groupId>
                <artifactId>mule-maven-plugin</artifactId>
                <version>${mule.maven.plugin.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <classifier>mule-application</classifier>
                    <cloudhub2Deployment>
                        <uri>https://anypoint.mulesoft.com</uri>
                        <provider>MC</provider>
                        <environment>Sandbox</environment>
                        <target>CloudHub-US-East-2</target> <!-- exact Runtime Manager target -->
                        <server>anypoint</server> <!-- server ID from settings.xml -->
                        <applicationName>${project.artifactId}</applicationName>
                        <releaseChannel>EDGE</releaseChannel>
                        <replicas>1</replicas>
                        <vCores>0.1</vCores>
                        <redeploy>true</redeploy>
                        <deploymentSettings>
                            <generateDefaultPublicUrl>true</generateDefaultPublicUrl>
                        </deploymentSettings>
                    </cloudhub2Deployment>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>anypoint-exchange-v3</id>
            <url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
        </repository>
    </repositories>

</project>
